version: "3.8"

services:
  nginx:
    build: 
      dockerfile: ./docker/nginx.dockerfile
      context: .  
    image: luisgs7/nginx_django:v1
    container_name: nginx
    ports:
      - "8000:8000"
    networks:
      - nwdjango
    depends_on:
      - django1
      - django2
      - django3

  pgdjango:
    build:
      dockerfile: ./docker/pgdjango.dockerfile
      context: .

    image: luisgs7/pgdjango:v1
    container_name: pgdjango
    ports:
      - "5432"
    networks:
      - nwdjango
    volumes:
      - pgdata:/home/luis/dev/django-docker/data
      # /home/luis/dev/django-docker/data /var/lib/postgresl/data

  django1:
    build:
      dockerfile: ./docker/django.dockerfile
      context: .
    image: luisgs7/django:v1
    container_name: django1
    ports:
      - "8000"
    networks:
      - nwdjango
    depends_on:
      - pgdjango

  
  django2:
    build:
      dockerfile: ./docker/django.dockerfile
      context: .
    image: luisgs7/django:v1
    container_name: django2
    ports:
      - "8000"
    networks:
      - nwdjango

    depends_on:
      - pgdjango


  django3:
      build:
        dockerfile: ./docker/django.dockerfile
        context: .
      image: luisgs7/django:v1
      container_name: django3
      ports:
        - "8000"
      networks:
        - nwdjango

      depends_on:
        - pgdjango

networks:
  nwdjango:
    driver: bridge


volumes:
  pgdata:
